More debugging statements

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -1,10 +1,34 @@
 #!/bin/sh
 
 # source some original files
+SCRIPT_DIR="$(dirname $0)"
 source /usr/local/s2i/s2i-setup
 source /usr/local/s2i/common.sh
 
 echo "s2i destination: ${S2I_DESTINATION}"
 echo "pwd:" `pwd`
+
+function check_error() {
+  local label=$1
+  local error=$2
+  if [ ${error} -ne 0 ]; then
+    echo "Aborting due to error code $error for $label"
+    exit ${error}
+  fi
+}
+
+function get_output_dir() {
+  local dir=""
+
+}
+
+# ############################################################################
+# Main
+
+echo "=========================================================="
+echo "Starting S2I Gradle Build ....
+build_dir=$(get_output_dir)
+check_error "Cannot get output dir: $build_dir" $?
 cd "${S2I_DESTINATION}"
+ls
 ./gradlew build test
